anguage: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: 422cb35f84f79490cb5f631a0fc54be544fb1ebf # a token generated on github allowing travis to push code on you repository
  target-branch: gh-pages
  keep-history: true
  on:
    branch: master