# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#  https://www.cnblogs.com/yangzhou33/p/11546713.html
#  https://sunburst.wang/posts/2019/03/20/deploying-to-github-pages-using-circle-ci-2-0.html
#  checkout 页面的 deploy key 只有读权限，没有写权限；如果要加入有读写权限的 deploy key，需要手动生成 ssh 然后到 ssh permission 页面去加。deploy key 只对特定仓库有权限。
#  user key 对你的账号下的所有仓库都有读写权限。
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

      # working_directory: ~/repo
    # only master branch will be deployed
    filters:
      branches:
        only: master

    steps:
      # connect to github by ssh
      - add_ssh_keys:
          fingerprints:
            - "a1:91:62:44:30:92:21:b3:ed:1f:e1:78:21:07:64:77"

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run deploy.sh!
      - run: yarn deploy